### ISSUE TITLE
Regression bug validationMetadatasToSchemas v5.0.0

### ISSUE THREAD

**Issue by hxtree** [epiphone/class-validator-jsonschema#100]
There appears to be a regression bug. The instructions provided in the readme work on 3.1.1 but do not work on version 5.0.0

```
// eslint-disable-next-line max-classes-per-file
import { Type } from 'class-transformer';
import { IsString, ValidateNested } from 'class-validator';
import { validationMetadatasToSchemas } from 'class-validator-jsonschema';

const { defaultMetadataStorage } = require('class-transformer/cjs/storage');

class BlogPost {
  @IsString()
  public words: string;
}

class User {
  @ValidateNested({ each: true })
  @Type(() => BlogPost)
  public blogPosts: BlogPost[];
}

const schemas = validationMetadatasToSchemas({
  classTransformerMetadataStorage: defaultMetadataStorage,
});
```

```
    TypeError: Cannot read properties of undefined (reading 'map')

      17 | }
      18 |
    > 19 | const schemas = validationMetadatasToSchemas({
         |                                             ^
      20 |   classTransformerMetadataStorage: defaultMetadataStorage,
      21 | });
      22 |

      at populateMetadatasWithConstraints (../../common/temp/node_modules/.pnpm/class-validator-jsonschema@5.0.0_e6kgdsnyya5caxg3ysdyxrqm7a/node_modules/class-validator-jsonschema/src/index.ts:146:20)
      at getMetadatasFromStorage (../../common/temp/node_modules/.pnpm/class-validator-jsonschema@5.0.0_e6kgdsnyya5caxg3ysdyxrqm7a/node_modules/class-validator-jsonschema/src/index.ts:137:23)
      at validationMetadatasToSchemas (../../common/temp/node_modules/.pnpm/class-validator-jsonschema@5.0.0_e6kgdsnyya5caxg3ysdyxrqm7a/node_modules/class-validator-jsonschema/src/index.ts:29:21)
      at Object.<anonymous> (src/__tests__/te.test.ts:19:45)     
```

When using version 5.0.0 the only way to call validationMetadatasToSchemas appears to be without any "()" or "({}".

**Comment by Luccazx12** [comment]
same here (with class-validator 0.14.0)
 return metadatas.map((meta) => {
app_1             |                      ^
app_1             | 
app_1             | TypeError: metadatas.map is not a function
app_1             |     at populateMetadatasWithConstraints (.../node_modules/class-validator-jsonschema/build/index.js:60:22)
app_1             |     at getMetadatasFromStorage (/(.../node_modules/class-validator-jsonschema/build/index.js:56:12)
app_1             |     at validationMetadatasToSchemas ((.../node_modules/class-validator-jsonschema/build/index.js:15:23

**Comment by Luccazx12** [comment]
same here (with class-validator 0.14.0)
```
 return metadatas.map((meta) => {
app_1             |                      ^
app_1             | 
app_1             | TypeError: metadatas.map is not a function
app_1             |     at populateMetadatasWithConstraints (.../node_modules/class-validator-jsonschema/build/index.js:60:22)
app_1             |     at getMetadatasFromStorage (/(.../node_modules/class-validator-jsonschema/build/index.js:56:12)
app_1             |     at validationMetadatasToSchemas ((.../node_modules/class-validator-jsonschema/build/index.js:15:23
```

**Comment by Luccazx12** [comment]
I was able to solve it as follows:

```
import * as oa from "openapi3-ts";
import { getMetadataArgsStorage, RoutingControllersOptions } from "routing-controllers";
import { routingControllersToSpec } from "routing-controllers-openapi";
import { validationMetadatasToSchemas } from "class-validator-jsonschema";

const metadataSchemas = validationMetadatasToSchemas();

const storage = getMetadataArgsStorage();
    return routingControllersToSpec(storage, routingControllersOptions, {
      components: {
        schemas: metadataSchemas as Record<string, oa.SchemaObject | oa.ReferenceObject>
      }
});
``

Com as libs nas versões: 

```
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "class-validator-jsonschema": "^5.0.0",
    "routing-controllers": "^0.10.1",
    "routing-controllers-openapi": "^4.0.0",
```

**Comment by Luccazx12** [comment]
I was able to solve it as follows:

```
import * as oa from "openapi3-ts";
import { getMetadataArgsStorage, RoutingControllersOptions } from "routing-controllers";
import { routingControllersToSpec } from "routing-controllers-openapi";
import { validationMetadatasToSchemas } from "class-validator-jsonschema";

const metadataSchemas = validationMetadatasToSchemas();

const storage = getMetadataArgsStorage();
    return routingControllersToSpec(storage, routingControllersOptions, {
      components: {
        schemas: metadataSchemas as Record<string, oa.SchemaObject | oa.ReferenceObject>
      }
});
```


Com as libs nas versões: 
```
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "class-validator-jsonschema": "^5.0.0",
    "routing-controllers": "^0.10.1",
    "routing-controllers-openapi": "^4.0.0",
```

**Comment by afraz-khan** [comment]
@mcankudis I upgraded `class-validator-jsonschema` to 5.0.0 but still finding [this](https://github.com/epiphone/routing-controllers-openapi/issues/139) issue.

**Comment by afraz-khan** [comment]
> same here (with class-validator 0.14.0)
> 
> ```
>  return metadatas.map((meta) => {
> app_1             |                      ^
> app_1             | 
> app_1             | TypeError: metadatas.map is not a function
> app_1             |     at populateMetadatasWithConstraints (.../node_modules/class-validator-jsonschema/build/index.js:60:22)
> app_1             |     at getMetadatasFromStorage (/(.../node_modules/class-validator-jsonschema/build/index.js:56:12)
> app_1             |     at validationMetadatasToSchemas ((.../node_modules/class-validator-jsonschema/build/index.js:15:23
> ```

@mcankudis I upgraded `class-validator-jsonschema` to 5.0.0 but still finding [this](https://github.com/epiphone/routing-controllers-openapi/issues/139) issue.

**Comment by gregkysenko** [comment]
Hello! Any updates for this issue? I am trying to integrate `class-validator-jsonschema` and It seem I can`t work with nested objects.

**Comment by Luccazx12** [comment]
> Hello! Any updates for this issue? I am trying to integrate `class-validator-jsonschema` and It seem I can`t work with nested objects.

For object arrays too

**Comment by osnipezzini** [comment]
anyone created some fork with this fix ?
